name: 'CD'

on: 
    push:
        branches: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPONAME }}

  deploy:
    name: deploy
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          sparse-checkout: config/scripts/deploy.sh 

    #   - name: create env file
    #     run: |
    #       touch .env
    #       echo "${{ secrets.ENV_VARS }}" >> .env
    #   - name: create remote directory
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.HOST }}
    #       username: ubuntu
    #       key: ${{ secrets.KEY }}
    #       script: mkdir -p /home/ubuntu/srv/ubuntu

    # 이거 고쳐야함 코드 개이상함 (by 김원욱)
      # - name: copy source via ssh key
      #   uses: burnett01/rsync-deployments@4.1
      #   with:
      #     switches: -avzr --delete
      #     remote_path: /home/ubuntu/srv/ubuntu/
      #     remote_host: ${{ secrets.HOST }}
      #     remote_user: ubuntu
      #     remote_key: ${{ secrets.KEY }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script_path: config/scripts/deploy.sh 